AllCops:
  NewCops: enable
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - config.ru
    - Gemfile.lock
    - Rakefile
    - node_modules/**/*
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Bundler/OrderedGems:
  Enabled: false

Layout/ClassStructure:
  ExpectedOrder:
    - module_inclusion
    - constants
    - association
    - public_attribute_macros
    - public_delegate
    - macros
    - public_class_methods
    - initializer
    - public_methods
    - protected_attribute_macros
    - protected_methods
    - private_attribute_macros
    - private_delegate
    - private_methods
Layout/EmptyLineAfterMultilineCondition:
  Enabled: true

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/LineLength:
  Exclude:
    - db/migrate/**/*
    - spec/**/*
  Max: 160

Layout/MultilineArrayBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineMethodDefinitionBraceLayout:
  EnforcedStyle: new_line

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/AssignmentInCondition:
  AllowSafeAssignment: false

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - app/services/**/*

Metrics/AbcSize:
  Max: 45

Metrics/BlockLength:
  Exclude:
    - config/routes.rb
    - lib/tasks/**/*
    - spec/**/*
  Max: 50

Metrics/BlockNesting:
  Exclude:
    - spec/**/*'
  Max: 4

Metrics/ClassLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Max: 250

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Exclude:
    - db/migrate/*.rb
    - spec/**/*'
  Max: 30

Metrics/ModuleLength:
  CountAsOne: ['array', 'hash', 'method_call', 'heredoc']
  Exclude:
    - spec/**/*'
  Max: 250

Metrics/PerceivedComplexity:
  Max: 10

Style/AutoResourceCleanup:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/CollectionMethods:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: true

Style/IpAddresses:
  Enabled: true

Style/MultilineMethodSignature:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 7

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SymbolArray:
  Enabled: false

Style/SymbolProc:
  AllowMethodsWithArguments: true

Style/WordArray:
  Enabled: false
